# Generated by Django 5.1.4 on 2025-01-06 09:51

import detector.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=detector.models.generate_random_filename),
        ),
    ]
